### ISSUE TITLE
nmap vs vmap ?

### ISSUE THREAD

**Issue by ctjhoa** [hecal3/vim-leader-guide#12]
Hi there,
I'm try to implement a leader mapping with different action if I'm in visual mode or not.
I'm using:
```
nmap <silent> <leader>j=  mzgg=G`z
vmap <silent> <leader>j=  ==
```
If I do that, the plugin always display 
```
mzgg=G`z
```
 but the behaviour is as intended.
So is there a way to customize the ouput of mapping (like a special comment or something)
or is there anyway equivalent with the `let g:lmap`  syntax ?
Thanks

**Comment by hecal3** [comment]
Thanks for reporting that.

This was indeed not working as intended. There was a bug in the visual mode detection.

**Comment by ctjhoa** [comment]
Nice thanks @hecal3  ! Is there a way to customize the ouput instead of display the mapping ?
If I want to display "reindent-buffer" instead of "mzgg=G`z"

**Comment by hecal3** [comment]
Yes, there are several possible solutions.

I'd recommend to use the following mappings:
```vim
nmap <silent> <SID>reindent-buffer mzgg=G`z
noremap <silent> <leader>j <SID>reindent-buffer
```
Then you can hide the `<SID>`-Prefix with the displayfunc.
See `:h leaderGuide_displayfunc`. The first example. Just replace <Plug> with <SID> (or add another substitute) and the example should work for your case. You can basically run arbitrary operations on the display text, `mzgg=G`z`

If you don't want to use a `<SID>` or `<Plug>` mapping, there is also the possibility to just use a simple lookup dictionary in the display function. It's shown in the second example.
