### ISSUE TITLE
Error message shown on pressing Space (dictionary required / list required)

### ISSUE THREAD

**Issue by lverweijen** [hecal3/vim-leader-guide#13]
The plugin works, but displays this error before displaying the mappings:

Error detected while processing function leaderGuide#start_by_prefix[9]..<SNR>12_start_parser[23
]..<SNR>12_add_map_to_dict[23]..<SNR>12_add_map_to_dict[32]..<SNR>12_flattenmap[9]..<SNR>12_flat
tenmap:
line    2:
E715: Dictionary required
E714: List required
Error detected while processing function leaderGuide#start_by_prefix[9]..<SNR>12_start_parser[23
]..<SNR>12_add_map_to_dict[23]..<SNR>12_add_map_to_dict[32]..<SNR>12_flattenmap[9]..<SNR>12_flat
tenmap[9]..<SNR>12_flattenmap:
line    2:
E715: Dictionary required
E714: List required
Error detected while processing function leaderGuide#start_by_prefix[9]..<SNR>12_start_parser[23
]..<SNR>12_add_map_to_dict[23]..<SNR>12_add_map_to_dict[32]..<SNR>12_flattenmap[9]..<SNR>12_flat
tenmap[9]..<SNR>12_flattenmap[9]..<SNR>12_flattenmap:
line    2:
E715: Dictionary required
E714: List required

Here a minimal configuration:
    let mapleader=" "
    let g:llmap = {}
    call leaderGuide#register_prefix_descriptions("<Space>", "g:llmap")
    call unite#filters#matcher_default#use(['matcher_fuzzy'])
    nnoremap <silent> <leader> :<c-u>LeaderGuide '<Space>'<CR>
    vnoremap <silent> <leader> :<c-u>LeaderGuideVisual '<Space>'<CR>
    nnoremap <leader>abc :dosomething<CR>

**Comment by hecal3** [comment]
I think your configuration example got messed up by github. As it is it looks wrong in any case.
Maybe you could enclose it with a ` `````vim ` block, or just paste it somewhere else.

**Comment by lverweijen** [comment]
It seems that the align-plugin is also a neccesity for this error to work.

I have made an extremely self-contained example [here](https://gist.github.com/lverweijen/2870addcc3af2dc8b0d2ccd427a027de#file-leadervimbug-vim).

Run it by:

    vim -u leadervimbug.vim

**Comment by hecal3** [comment]
Thanks, from what I can tell this is another one of those conflict issues.
The align-plugin defines:
```vim
map <unique> <Leader>aunum <Plug>AM_aunum
```
This somewhat conflicts with your mapping
```vim
nnoremap <Leader>au :dosomething<CR>
```
It's not possible to display those two in a strictly hierarchical manner.

If you don't set `let g:leaderGuide_flatten = 0` those two mappings should be displayed side by side in the `<leader>a`-menu. Apparently this does not work here. If I had to guess I'd say its because the difference in length between the mappings is greater than 1. A bug in any case.
I'll take a closer look later.

**Comment by hecal3** [comment]
Should be fixed with the latest commit.
I forgot to handle the "name" attribute in the dictionaries.
And it indeed only showed when the difference between the mapping length was >1.
