### ISSUE TITLE
Set Window Size

### ISSUE THREAD

**Issue by khalidchawtany** [hecal3/vim-leader-guide#14]
I have a lot of mappings and when using which key I cannot see what I am working on.
Is it possible to set a window size and just show what fits inside? The remaining mappings would be shown using a **Ctrl-z_n** submode as in which keys.

**Comment by hecal3** [comment]
I'm afraid this is currently not possible.

I'll have to take a look at which-key to see how they do it. Apparently they have some kind of paging feature to allow cycling through multiple pages without loosing the key sequence.

Should be doable to add some command mode mapping to do that. I will take a stab at this when I find some time.

**Comment by hecal3** [comment]
I just pushed a attempt at this to the paging branch. Maybe you can try it out.

Configuration example:
```vim
let g:leaderGuide_max_size = 5
let g:leaderGuide_submode_mappings = { '<C-C>': 'win_close', '<C-F>': 'page_down', '<C-B>': 'page_up'}
```
`<C-C><C-F>` for page down
`<C-C><C-B>` for page up
`<C-C><C-C>` to close the guide. (Old `<C-C>` behaviour)

**Comment by khalidchawtany** [comment]
Thanks. It works nicely 👍
