### ISSUE TITLE
Installation - pathogen

### ISSUE THREAD

**Issue by adrsta** [hecal3/vim-leader-guide#15]
Is it possible to install with Pathogen?
because I tried and it doesn't seem to work

**Comment by hecal3** [comment]
Sorry for the delay.
I did not test this with pathogen specifically, but I see no reason it shouldn't work. Other common plugin managers do.

Are you sure that you did the required configurations or called a valid command? On it's own the plugin does nothing after all.

**Comment by adrsta** [comment]
Nevermind that. I switched to vim-plug, and the installation works.
