### ISSUE TITLE
Does not work without configuration

### ISSUE THREAD

**Issue by metakirby5** [hecal3/vim-leader-guide#19]
Contrary to the claim that "it is possible to call the guide without any configuration", an empty prefix description dict must be registered, or else the following error occurs:

```
Error detected while processing function leaderGuide#start_by_prefix:
line    6:
E121: Undefined variable: s:cached_dicts
E116: Invalid arguments for function has_key(s:cached_dicts, a:key) || g:leaderGuide_run_map_on_popup
E15: Invalid expression: !has_key(s:cached_dicts, a:key) || g:leaderGuide_run_map_on_popup
line   12:
E121: Undefined variable: s:desc_lookup
E116: Invalid arguments for function has_key(s:desc_lookup, a:key) || has_key(s:desc_lookup , 'top')
E15: Invalid expression: has_key(s:desc_lookup, a:key) || has_key(s:desc_lookup , 'top')
line   18:
E121: Undefined variable: rundict
E116: Invalid arguments for function <SNR>123_start_buffer
```

Minimal `.vimrc` to reproduce the problem, assuming `vim-plug` is installed:

```vim
call plug#begin('~/.vim/plugins')
  Plug 'hecal3/vim-leader-guide'
call plug#end()

nnoremap <silent> [ :<c-u>LeaderGuide '['<CR>
vnoremap <silent> [ :<c-u>LeaderGuideVisual '['<CR>

nmap [e <esc>:echo "hello world"<cr>
```

Steps to reproduce problem:

1. Run `vim`
2. Quickly type `[e` and observe that `hello world` is echoed
3. Type `[` and wait for the leader guide to show up
4. Observe that the aforementioned error occurs

To "fix" this issue, the following must be placed into the `.vimrc`:

```vim
let g:lgmap = {}
call leaderGuide#register_prefix_descriptions('', 'g:lgmap')
```

**Comment by hecal3** [comment]
I believe it will be solved with #27 (Default values for a leader and localleader dictionary)

Of course it will still be neccessary to use some manual configuration for keys other than leader and localleader like your example above.

**Comment by metakirby5** [comment]
Wouldn't it be possible to use an empty dictionary for all prefixes by default? Ideally when nothing is configured, no error messages should leak out.

**Comment by hecal3** [comment]
Yes, that's what I did in the end.
The snippet in #27 proved to be a bit fickle and would stop working for special keys or if either leader or localleader wasn't set.

**Comment by z0rc** [comment]
Is it possible to somehow amend this? I'm trying to migrate my vim configuration to native packages and this code change gives me a hard time.

With pathogen I'm able to do `call leaderGuide#register_prefix_descriptions` in vimrc, but using native packaging fails to do so, because load order is changed. Native packaging adds autoload to `runtimepath` only after vimrc is sourced. This leads to situation when plugin starts with empty description map and it's impossible to override this in configuration loaded `after` plugin.

**Comment by z0rc** [comment]
Okay, disregard my last comment. I managed to figure it out, everything is good now, nothing needs to be changed from your side, sorry for the noise.
