### ISSUE TITLE
Set nolist to disable trailing whitespace indicator

### ISSUE THREAD

**Issue by wooken** [hecal3/vim-leader-guide#2]
As a temporary fix, I'm just throwing it here:

```
execute "normal! i ".join(string,'')
setlocal nomodifiable
setlocal nolist
```

**Comment by hecal3** [comment]
Thanks. Sorry for the delay, I completly forgot about this over the holidays.

**Comment by wooken** [comment]
Thanks for the change! Excellent plugin, btw =]
