### ISSUE TITLE
Suggestion: Use mapleader/maplocalleader in README

### ISSUE THREAD

**Issue by xu-cheng** [hecal3/vim-leader-guide#27]
Instead of assuming users have <kbd>SPACE</kbd> as the leader, you can use `mapleader` to get the current setting(the same goes for `maplocalleader`), e.g.:

``` vim
let g:vim_leader_guide_map = {
            \   mapleader: {
            \       'name': '<leader>',
            \   },
            \   maplocalleader: {
            \       'name': '<localleader>',
            \   },
            \ }
autocmd FileType tex let g:vim_leader_guide_map[maplocalleader].l = { 'name': 'Vimtex' }
call leaderGuide#register_prefix_descriptions('', 'g:vim_leader_guide_map')

nnoremap <silent> <leader> :<C-u>LeaderGuide mapleader<CR>
vnoremap <silent> <leader> :<C-u>LeaderGuideVisual mapleader<CR>
map <leader>. <Plug>leaderguide-global
nnoremap <localleader> :<C-u>LeaderGuide maplocalleader<CR>
vnoremap <localleader> :<C-u>LeaderGuideVisual maplocalleader<CR>
map <localleader>. <Plug>leaderguide-buffer
```

In fact, you can set the key binding for users directly. So one can use this plugin without any configuration.

**Comment by hecal3** [comment]
Good catch, I will set the dictionary as default.
This will also require a slight rework of the readme and documentation, to reflect the different configuration and not sweep the more advanced features such as swapping out dictionaries on filetype changes under the rug.

As far as mappings go, I am a bit reluctant to use default values here. Especially for leader and localleader, which are really the users namespace.

**Comment by hecal3** [comment]
When used with Space as a leader key the settings above do not work correctly. This would require some additional logic.
I'm not sure about other 'special' leader keys such as `<Tab>`.

Additionally we'd have to check if leader and localleader are set in the first place.

Not sure if all that is really worth the effort.

**Comment by hecal3** [comment]
Closing for now.
As it stands, a default configuration as above assumes too much about the users setup.
Adding a few lines is not really an issue.
