### ISSUE TITLE
Error when pressing space

### ISSUE THREAD

**Issue by Stocki** [hecal3/vim-leader-guide#3]
I get following error message in vim when i press space:

Fehler beim Ausführen von "function leaderGuide#start_by_prefix..<SNR>24_start_guide..<SNR>24_start_buffer..<SNR>24_create_string":
Zeile    5:
E117: Unbekannte Funktion: i
E702: Die Vergleichsfunktion der Sortierung ist fehlgeschlagen

Translation (by me)
Error executing "function leaderGuide#start_by_prefix..<SNR>24_start_guide..<SNR>24_start_buffer..<SNR>24_create_string":
Line    5:
E117: Unknown function: i
E702: The compare function of sort failed

**Comment by hecal3** [comment]
I just took a quick glance at the vim changelogs. Are you on version 7.4.341 or earlier?

Apparently there has been a change in the sort() function.
Prior to patch 341 'i' is not a valid flag. Replacing 'i' with '1' should do the trick.

**Comment by Stocki** [comment]
Wow that was a quick answer... 
And indeed I am on a earlier version and changing the flag to 1 did the trick!

Great plugin btw! Love it!

**Comment by hecal3** [comment]
Thanks.
Trying an older version myself is a bit of a hassle when it's not in the package repos. Fortunately it was an easy fix like this.
