### ISSUE TITLE
clear cmdline after execute mappings.

### ISSUE THREAD

**Issue by wsdjeg** [hecal3/vim-leader-guide#33]
![2017-01-24_1362x724](https://cloud.githubusercontent.com/assets/13142418/22252453/354ef910-e289-11e6-957f-71c96c04ec05.png)

I type `\j`, and wait for the timeout. then the guide is opened. then I type `g` to execute one mapping in the guide. but after execute I still can see `g` in the cmdline, I hope the cmdline can be clear up after execute mapping.

**Comment by wsdjeg** [comment]
and my plugin, vim-chat use same feature to build the prompt. you can see my plugin.
https://github.com/vim-chat/vim-chat

and I clear cmdline by 
```viml
function! s:echon() abort
    redraw!
    echohl Comment | echon s:c_base   " cmdline prompt
    echohl None | echon s:c_begin    " chars before cursor
    echohl Wildmenu | echon s:c_char   " char under the cursor
    echohl None | echon s:c_end     " chars after corsor
endfunction
```

**Comment by wsdjeg** [comment]
I want to use this plugin in https://github.com/SpaceVim/SpaceVim, and I will try to send a pr.

**Comment by hecal3** [comment]
Sorry for the delay.
I'm not quite sure about simply clearing the cmdline after the guide is closing.

I'd not be possible to use a command explicitly printing to the commandline anymore. E.g.
```vim
nnoremap <leader>z :pwd<CR>
```

Maybe you could trigger the redraw manually for those mappings where you want it?
```vim
nnoremap <leader>z :pwd<CR>:redraw!<CR>
```
I you want to clear the line for all mappings we could add some User-autocmd hook to execute own code after the guide closes.

**Comment by wsdjeg** [comment]
user autocmd will be better I think. I have too many mappings, I do not want to add `:redraw!<cr>` to the end of each one.
