### ISSUE TITLE
clipboard is cleared when open guide window.

### ISSUE THREAD

**Issue by chenzhihuai1990** [hecal3/vim-leader-guide#38]
I firstly yank a line with command `yy`, then I press `<space>` which I use as my leader key.
Finally, I found my register/clipboard is cleared.

**Comment by wsdjeg** [comment]
```diff
-normal! ggdd
+normal! gg"_dd
```

**Comment by wsdjeg** [comment]
@hecal3 
https://github.com/hecal3/vim-leader-guide/blob/master/autoload/leaderGuide.vim#L315

**Comment by hecal3** [comment]
Should be fixed, thanks for the suggestion.
