### ISSUE TITLE
Run some functions before leader guide show?

### ISSUE THREAD

**Issue by chenzhihuai1990** [hecal3/vim-leader-guide#43]
Is it possible do some operations before the leader guide panel show?
I try to map `<leader>c1`...`<leader>c9` to close corresponding buffer/window. However, since the buffers is changing all the time, I think I should remap them when they change.
This maybe can be done by `autocmd`, but in some special situation,  calling before panel show will be better.

**Comment by hecal3** [comment]
Almost a year late, but here it is: 8dff63fcc29811bb30fccb135f31ad488a9a6170

The added function is run right before the the panel opens.
It's possible to modify the dictionary the guide is called with at this point. (For this one call only, the global options remain unchanged)

```vim
function! s:leaderGuide_before_open()
    " Context, from witch the trigger was called.
    " contains values such as type, name, original window number, visual (y/n)
    " , current tree level, etc
    "
    " echom string(g:leaderGuide#context)
    let context = g:leaderGuide#context

    if &ft == 'vim'
        echom 'guide to be called from a vim-buffer'
    endif

    let guide_dictionary = get(g:leaderGuide#context, 'display')
    let level = get(g:leaderGuide#context, 'level')
    if level == 1 && has_key(guide_dictionary, 'g')
        call remove(guide_dictionary, 'g')
    endif
endfunction
call leaderGuide#add_trigger('before_open', function("s:leaderGuide_before_open"))
```
