### ISSUE TITLE
jumping to top of file on unknown binding

### ISSUE THREAD

**Issue by vitaly** [hecal3/vim-leader-guide#48]
When an unknown binding is encountered, leader-guide will jump to the top of the buffer, instead of ignoring the binding.

**Comment by spinks** [comment]
Hi!
I have a fork where I believe this is fixed, check https://github.com/spinks/vim-leader-guide/commit/9c0b345f07d767725c5eae955e6a1792d22f18ce to see the fix.

This works in combination with https://github.com/spinks/vim-leader-guide/commit/d8363bdcec5cc484cae83848a474bcbd7aaa7a40 which makes the menu wait for a correct input.
