### ISSUE TITLE
Set command args after typing

### ISSUE THREAD

**Issue by ctjhoa** [hecal3/vim-leader-guide#9]
Hi there,

So my goal is to add a mapping on a "rename current buffer file" function.
I've got my `Rename` function but I don't understand how set my arg (the new name) after having typed my mapping.
Can I acheive this with this plugin.

Thanks.

**Comment by hecal3** [comment]
Are you perhaps looking for something like this?
```vim
function! Renamebuffer()
    let newname = input("Enter new name: ")
    echo newname
    " Do stuff with newname
endfunction

noremap <leader>r :call Renamebuffer()<CR>
```
With input() you can query text from the cmdline from inside of a function. Or do you want to pass an argument to the function directly?

**Comment by ctjhoa** [comment]
Nice it's works ! Thanks.
I'm using [tpope/vim-eunuch](https://github.com/tpope/vim-eunuch) to provide basic UNIX methods.
I'm newbie to VimScript but what I'm initially looking for is to pass an argument to the command directly. For example `:Rename new_name`. This avoid me to wrap each `vim-eunuch` command.

Now I do:
```
function! RenameWrapper()
    let buf = input("Rename Current Buffer File: ")
    execute "Rename" buf
endfunction

let g:lmap.f.R = ['silent call RenameWrapper()', 'rename-current-buffer-file']
```

**Comment by hecal3** [comment]
I believe there are several ways to accomplish that.
The most basic mapping would be:
```vim
noremap <leader>fR :Rename 
```
Note that there is a whitespace behind :Rename and the lack of `<CR>`.
This way when pressing the map, :Rename will appear in the cmdline. The user can then type the new name and press enter.

If you want to provide a more descriptive mapping to show in the guide, you could use a `<Plug>`-mapping like this:
```vim
noremap <Plug>rename-current-buffer-file :Rename 
nmap <leader>fR <Plug>rename-current-buffer-file
```
That is what I would use probably. Maybe I should include an option to hide the `<Plug>`-prefix in the guide.

And lastly, if you want to use the configuration dictionary:
```vim
let g:lmap.f.R = ['call feedkeys(":Rename ")', 'rename-current-buffer-file']
```
It is possible to feed vim pretty much anything with feedkeys(). In simple cases like this the usage is easy enought.

For more complex cases you might want to read up the documentation on feedkeys(). How to handle character-esacpes and mappings and such.
